import type { Metadata } from "next"

import "@/app/styles/globals.css"
import {
  inter,
  geistSans,
  geistMono,
} from "@/app/fonts"
import {
  ThemeProvider,
  QueryProvider,
} from "@/app/providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
